In [1]:
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#reshape and view
my_torch.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
#reshape
my_torch=my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10000)
my_torch3 = my_torch2.reshape(10,-1)
my_torch3

tensor([[   0,    1,    2,  ...,  997,  998,  999],
        [1000, 1001, 1002,  ..., 1997, 1998, 1999],
        [2000, 2001, 2002,  ..., 2997, 2998, 2999],
        ...,
        [7000, 7001, 7002,  ..., 7997, 7998, 7999],
        [8000, 8001, 8002,  ..., 8997, 8998, 8999],
        [9000, 9001, 9002,  ..., 9997, 9998, 9999]])

In [6]:
#changes in my_torch2 or rignal will also change the reshape or view
my_torch2[0]=1000
my_torch3

tensor([[1000,    1,    2,  ...,  997,  998,  999],
        [1000, 1001, 1002,  ..., 1997, 1998, 1999],
        [2000, 2001, 2002,  ..., 2997, 2998, 2999],
        ...,
        [7000, 7001, 7002,  ..., 7997, 7998, 7999],
        [8000, 8001, 8002,  ..., 8997, 8998, 8999],
        [9000, 9001, 9002,  ..., 9997, 9998, 9999]])

In [7]:
#slices same as list
my_torch3[0,1:3]#output is tensor

tensor([1, 2])

In [8]:
my_torch3[:,1]

tensor([   1, 1001, 2001, 3001, 4001, 5001, 6001, 7001, 8001, 9001])

In [9]:
# output as coukmn
my_torch3[:,1:2] #: remain the shape

tensor([[   1],
        [1001],
        [2001],
        [3001],
        [4001],
        [5001],
        [6001],
        [7001],
        [8001],
        [9001]])

# tensor algebra


In [10]:
# tensor addition
my_torch4 = torch.arange(10)
my_torch5 = torch.arange(2,12)
my_torch6 = my_torch4 + my_torch5
my_torch6

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
#by add method
my_torch7 = torch.add(my_torch4,my_torch5)
my_torch7


tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])


**' same for subtraction and fxn in sub() '**
**' same for multiplication and division fxn are mul and dev()'**

In [12]:
#modulus
my_torch8 = torch.arange(10)
my_torch9 = torch.arange(2,12)
my_torch10 = my_torch8 % my_torch9
my_torch10#remainder

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#longhand
my_torch11 = torch.remainder(my_torch8,my_torch9)
my_torch11


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#exponetial
my_torch12=torch.pow(my_torch8,my_torch9)
my_torch12

tensor([          0,           1,          16,         243,        4096,
              78125,     1679616,    40353607,  1073741824, 31381059609])

In [15]:
#adition to my_torch8 in my_torch9 and store in my_torch8
my_torch8.add_(my_torch9)
#note the underscore it will change the value of my_torch8


tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [17]:
my_torch8#billo

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])