# beginning of pytorch

Machine Learning (ML) and Deep Learning (DL) are both subfields of Artificial Intelligence (AI) that involve training models to make predictions or perform tasks based on data. However, there are some key differences between ML and DL:

1. **Representation of Data**: In ML, data is typically represented using handcrafted features that are extracted from the raw data. These features are then used as input to the ML model. In DL, the model learns to automatically extract features from the raw data, eliminating the need for manual feature engineering.

2. **Model Complexity**: ML models are usually simpler and have fewer parameters compared to DL models. DL models, on the other hand, are more complex and have a larger number of parameters. This allows DL models to learn more intricate patterns and relationships in the data.

3. **Training Data Size**: ML models can perform well with smaller training datasets. DL models, on the other hand, typically require larger amounts of training data to generalize effectively. DL models thrive on big data and can benefit from large-scale datasets.

4. **Computational Requirements**: DL models are computationally more intensive compared to ML models. DL models often require specialized hardware, such as Graphics Processing Units (GPUs), to train efficiently. ML models can be trained on standard hardware.

5. **Domain Expertise**: ML models often require domain expertise to engineer relevant features and select appropriate algorithms. DL models, on the other hand, can automatically learn features from the data, reducing the need for extensive domain knowledge.

6. **Interpretability**: ML models are generally more interpretable compared to DL models. ML models often provide insights into the importance of different features and how they contribute to the predictions. DL models, due to their complexity, are often considered as "black boxes" and provide less interpretability.

It's important to note that ML and DL are not mutually exclusive, and DL is a subset of ML. DL techniques, such as deep neural networks, have shown remarkable success in various domains, including computer vision, natural language processing, and speech recognition. However, ML techniques still have their place in scenarios where interpretability, smaller datasets, or limited computational resources are important considerations.


In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_log_error
from sklearn.metrics import explained_variance_score
from sklearn.metrics import max_error

In [2]:
# vector
vec=torch.tensor([1.0,2.0,3.0,4.0,5.0])
vec.ndim

1

In [3]:
#create matrix
mat=torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(mat)
mat.ndim

tensor([[1., 2., 3.],
        [4., 5., 6.]])


2

In [4]:
#3d tensor
tens=torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tens)
tens.ndim

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


3

In [5]:
tens.dtype

torch.int64

In [6]:
#4d tensor
tens4d=torch.tensor([[[[1.0,2.0],[3.0,4.0]],[[5.0,6.0],[7.0,8.0]]],[[[9.0,10.0],[11.0,12.0]],[[13.0,14.0],[15.0,16.0]]]])
print(tens4d)
tens.ndim

tensor([[[[ 1.,  2.],
          [ 3.,  4.]],

         [[ 5.,  6.],
          [ 7.,  8.]]],


        [[[ 9., 10.],
          [11., 12.]],

         [[13., 14.],
          [15., 16.]]]])


3

### random tensor


In [7]:

rand3dtensor=torch.rand(3,3,2)#create a random 3d tensor
rand3dtensor

tensor([[[0.2751, 0.3309],
         [0.0969, 0.7469],
         [0.4730, 0.4074]],

        [[0.2959, 0.0028],
         [0.4532, 0.9231],
         [0.8467, 0.6553]],

        [[0.4918, 0.9490],
         [0.0654, 0.3991],
         [0.3111, 0.3516]]])

In [8]:
rand3dtensor.shape

torch.Size([3, 3, 2])

In [9]:
#5d random tensor
rand5dtensor=torch.rand(2,3,4,5,6)
rand5dtensor

tensor([[[[[9.5775e-02, 5.3850e-01, 5.8156e-01, 2.3919e-01, 5.3811e-01,
            3.5715e-01],
           [3.0752e-01, 7.2882e-01, 4.8394e-01, 1.6214e-01, 9.3413e-01,
            6.6962e-01],
           [2.0804e-01, 1.3911e-01, 6.7715e-01, 1.5241e-01, 1.7841e-01,
            1.1562e-01],
           [5.6969e-01, 5.5312e-01, 4.9397e-01, 4.1216e-01, 8.3389e-01,
            9.0965e-01],
           [3.0470e-01, 1.5882e-01, 8.5260e-01, 9.4303e-01, 6.4691e-01,
            2.4861e-01]],

          [[6.9817e-01, 9.4190e-01, 8.0178e-01, 9.6321e-04, 8.7296e-01,
            5.8363e-02],
           [2.6293e-01, 9.1104e-01, 6.6351e-01, 8.9925e-01, 1.5148e-01,
            3.8147e-01],
           [5.7087e-01, 7.6348e-01, 8.5531e-01, 4.4312e-01, 3.0807e-01,
            7.3935e-01],
           [1.1277e-01, 1.9859e-01, 5.7023e-01, 7.4033e-01, 2.5312e-02,
            5.4974e-01],
           [6.0333e-01, 1.7152e-01, 1.7703e-01, 9.8963e-01, 3.8065e-01,
            1.9811e-01]],

          [[2.7767e-01, 4.

In [10]:
#zero tensor
zero_tensor=torch.zeros(3,3,3)
zero_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

### data types

In [11]:
zero_tensor.dtype

torch.float32

In [12]:
#float 16 tensor
float16_tensor=torch.zeros(3,3,3,dtype=torch.float16)
float16_tensor.dtype

torch.float16

In [13]:
#float 64 tensor
float64_tensor=torch.zeros(3,3,3,dtype=torch.float64)
float64_tensor.dtype

torch.float64

In [14]:
float16_tensor*float64_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)

In [15]:
# int tensor
int_tensor=torch.tensor([1,2,3,4,5])#default int tensor is int64
int_tensor.dtype

torch.int64

In [16]:
#32 bit int tensor
int32_tensor=torch.tensor([1,2,3,4,5],dtype=torch.int32)#for 16 bit use torch.int16 and for 64 bit use torch.int64


In [17]:
#def function to check dtype device and shape of tensor
def describe_tensor(tensor):
    print(f"Shape of tensor: {tensor.shape}")
    print(f"Datatype of tensor: {tensor.dtype}")
    print(f"Device tensor is stored on: {tensor.device}")


In [18]:
describe_tensor(int32_tensor)

Shape of tensor: torch.Size([5])
Datatype of tensor: torch.int32
Device tensor is stored on: cpu


### tensor manipulating

tensor opretions include:
* airthmatic alzebra
* matrix multipliction



In [19]:
#addition
int_tensor=torch.tensor([1,2,3,4,5])
int_tensor+10

tensor([11, 12, 13, 14, 15])

In [20]:
#multiplication
int_tensor*10

tensor([10, 20, 30, 40, 50])

In [21]:
#by pytorch inbuilt function
torch.add(int_tensor,10)

tensor([11, 12, 13, 14, 15])

In [22]:
torch.mul(int_tensor,10)

tensor([10, 20, 30, 40, 50])

### matrix multiplication
* matrix multiplication 
* elemental multiplication

In [23]:
# element wise multiplication
a=torch.tensor([1,2,3,4,5])
b=torch.tensor([10,20,30,40,50])
a*b

tensor([ 10,  40,  90, 160, 250])

In [24]:
# element wise multiplication in 2d tensor
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.tensor([[10,20,30],[40,50,60]])
print(a,'*',b,)
print(f"equals:{a*b}")

tensor([[1, 2, 3],
        [4, 5, 6]]) * tensor([[10, 20, 30],
        [40, 50, 60]])
equals:tensor([[ 10,  40,  90],
        [160, 250, 360]])


matrix multiplication

In [25]:
#matrix multiplication
a=torch.tensor([[1,2,3],[4,5,6]])#2x3
b=torch.tensor([[10,20],[30,40],[50,60]])#3x2
torch.matmul(a,b)

tensor([[220, 280],
        [490, 640]])

## stat of tensor

In [26]:
# finding mean, max, min, sum, std 2d tensor
def stat_tensor(tensor):
    print(f"Shape of tensor: {tensor.shape}")
    print(f"Datatype of tensor: {tensor.dtype}")
    print(f"Device tensor is stored on: {tensor.device}")
    print(f"Mean: {tensor.mean()}")# means works on float tensor
    print(f"Max: {tensor.max()}")
    print(f"Min: {tensor.min()}")
    print(f"Sum: {tensor.sum()}")
    print(f"Standard Deviation: {tensor.std()}")
a=torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]])
stat_tensor(a)

Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Mean: 3.5
Max: 6.0
Min: 1.0
Sum: 21.0
Standard Deviation: 1.8708287477493286


In [27]:
# finding positional max and min
def pos_max_min(tensor):
    print(f"Shape of tensor: {tensor.shape}")
    print(f"Datatype of tensor: {tensor.dtype}")
    print(f"Device tensor is stored on: {tensor.device}")
    print(f"Max: {tensor.max()}")
    print(f"Position of Max: {tensor.argmax()}")
    print(f"Min: {tensor.min()}")
    print(f"Position of Min: {tensor.argmin()}")
a=torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]])
pos_max_min(a)

Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Max: 6.0
Position of Max: 5
Min: 1.0
Position of Min: 0


## reshaping


In [28]:
# reshaping
a=torch.tensor([[1,2,3],[4,5,6]])
print("reshaped to 3,2")
z=a.reshape(3,2)
z

reshaped to 3,2


tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [29]:
# view changes the shape of tensor
a=torch.tensor([[1,2,3],[4,5,6]])
print("viewed to 3,2")
view_a=a.view(3,2)
view_a

viewed to 3,2


tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [30]:
print("initial a tensor",a)
view_a[0,0]=100
print("chaning view_a will change a",a)

initial a tensor tensor([[1, 2, 3],
        [4, 5, 6]])
chaning view_a will change a tensor([[100,   2,   3],
        [  4,   5,   6]])


In [31]:
# stacking tensors
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
torch.stack((a,b),dim=0)#dimention 0 means stacking row wise

tensor([[1, 2, 3],
        [4, 5, 6]])

In [32]:
torch.stack((a,b),dim=1)#dimention 1 means stacking column wise

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [33]:
#stacking 2d tensors to 3d tensor
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.tensor([[7,8,9],[10,11,12]])
torch.stack((a,b),dim=0)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [34]:
#SQUEEZING AND UNSQUEEZING TENSORS
a=torch.tensor([[[1,2,3],[4,5,6]]])
print(a,a.shape)
"squezed",a.squeeze(),a.squeeze().shape#removes the dimension of size 1

tensor([[[1, 2, 3],
         [4, 5, 6]]]) torch.Size([1, 2, 3])


('squezed',
 tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [35]:
# torch unsquezzing
a=torch.tensor([[1,2,3],[4,5,6]])
print(a,a.shape)
"unsqueezed",a.unsqueeze(dim=0),a.unsqueeze(dim=0).shape#adds a dimension of size 1 at the specified position

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])


('unsqueezed',
 tensor([[[1, 2, 3],
          [4, 5, 6]]]),
 torch.Size([1, 2, 3]))

In [36]:
# permute - rearranges the dimensions of tensor eg: 3d tensor to 2d tensor
x_org=torch.rand(2,3,4)#3d tensor of size 224x224x3 indicating 224x224 image with 3 channels(hieght, width, channels)
# we permute the tensor to 3x224x224
x_permute=x_org.permute(2,0,1)#(2=channels, 0=height, 1=width)
print("x_org shape",x_org.shape,"x_permute shape",x_permute.shape)

x_org shape torch.Size([2, 3, 4]) x_permute shape torch.Size([4, 2, 3])


## indexing and slicing
* same as numpy

In [37]:

x=torch.arange(6).view(2,3)
print(x)
print(x[1,2])#indexing
print(x[1:])#slicing

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor(5)
tensor([[3, 4, 5]])


## pytorch tensor & numpy array
* data in numpy ,want in pytorch tensor -> `torch.from_numpy(ndarray)`
* data in pytorch tensor ,want in numpy array -> `tensor.numpy()`

In [38]:
#numpy to tensor
np_array=np.arange(1.0,10.0)
tensor=torch.from_numpy(np_array).type(torch.float32)#tensor is copy of numpy array so changing tensor will not change numpy array
tensor,tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

## reproduciblity
As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.
Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic (each step is predictable) so the randomness they create are simulated randomness (though there is debate on this too, but since I'm not a computer scientist, I'll let you find out more yourself).
How does this relate to neural networks and deep learning then?
We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.
In short:

`start with random numbers -> tensor operations -> try to make better (again and again and again)`

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.
Why?
So you can perform repeatable experiments.
For example, you create an algorithm capable of achieving X performance.
And then your friend tries it out to verify you're not crazy.
How could they do such a thing?
That's where reproducibility comes in.
In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?
Let's see a brief example of reproducibility in PyTorch.
We'll start by creating two random tensors, since they're random, you'd expect them to be different right?
has context menu
Compose
Karan Singh is typing

In [39]:
#reproducibility
random_tensor_A=torch.rand(3,3)
random_tensor_B=torch.rand(3,3)
random_tensor_A==random_tensor_B

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [40]:
#build some reproducible tensor
random_seed=42
torch.manual_seed(random_seed)#set seed for reproducibility
##print("Random tensor A")
random_tensor_c=torch.rand(3,3)
torch.manual_seed(random_seed) ### we set the seed again to make sure the random tensor is reproducible###
random_tensor_d=torch.rand(3,3)
print("Random tensor c",random_tensor_c,"\nRandom tensor d",random_tensor_d)
random_tensor_c==random_tensor_d

Random tensor c tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]]) 
Random tensor d tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## gpu acessing

In [41]:
#check if cuda is available
torch.cuda.is_available()


True

In [42]:
# setup device agnostic code
device='cuda' if torch.cuda.is_available() else 'cpu'

In [43]:
# no of gpu's available
torch.cuda.device_count()

1

### putting tensor on gpu 

In [44]:
tensor=torch.rand(3,3)
tensor.device,device

(device(type='cpu'), 'cuda')

In [45]:
# move tensor to gpu
tensor_on_gpu=tensor.to(device)

In [46]:
# tensor on gpu cant tranform into numpy
try:
    tensor_on_gpu.numpy() 
except Exception as e:
    print(e)

can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.


In [47]:
# GPU TENSOR YO NUMPY
tensor_on_gpu.cpu().numpy()

array([[0.13318592, 0.9345981 , 0.59357965],
       [0.86940444, 0.5677153 , 0.74109405],
       [0.4294045 , 0.8854429 , 0.57390445]], dtype=float32)