# beginning of pytorch

Machine Learning (ML) and Deep Learning (DL) are both subfields of Artificial Intelligence (AI) that involve training models to make predictions or perform tasks based on data. However, there are some key differences between ML and DL:

1. **Representation of Data**: In ML, data is typically represented using handcrafted features that are extracted from the raw data. These features are then used as input to the ML model. In DL, the model learns to automatically extract features from the raw data, eliminating the need for manual feature engineering.

2. **Model Complexity**: ML models are usually simpler and have fewer parameters compared to DL models. DL models, on the other hand, are more complex and have a larger number of parameters. This allows DL models to learn more intricate patterns and relationships in the data.

3. **Training Data Size**: ML models can perform well with smaller training datasets. DL models, on the other hand, typically require larger amounts of training data to generalize effectively. DL models thrive on big data and can benefit from large-scale datasets.

4. **Computational Requirements**: DL models are computationally more intensive compared to ML models. DL models often require specialized hardware, such as Graphics Processing Units (GPUs), to train efficiently. ML models can be trained on standard hardware.

5. **Domain Expertise**: ML models often require domain expertise to engineer relevant features and select appropriate algorithms. DL models, on the other hand, can automatically learn features from the data, reducing the need for extensive domain knowledge.

6. **Interpretability**: ML models are generally more interpretable compared to DL models. ML models often provide insights into the importance of different features and how they contribute to the predictions. DL models, due to their complexity, are often considered as "black boxes" and provide less interpretability.

It's important to note that ML and DL are not mutually exclusive, and DL is a subset of ML. DL techniques, such as deep neural networks, have shown remarkable success in various domains, including computer vision, natural language processing, and speech recognition. However, ML techniques still have their place in scenarios where interpretability, smaller datasets, or limited computational resources are important considerations.


In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_log_error
from sklearn.metrics import explained_variance_score
from sklearn.metrics import max_error

In [2]:
# vector
vec=torch.tensor([1.0,2.0,3.0,4.0,5.0])
vec.ndim

1

In [3]:
#create matrix
mat=torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(mat)
mat.ndim

tensor([[1., 2., 3.],
        [4., 5., 6.]])


2

In [4]:
#3d tensor
tens=torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tens)
tens.ndim

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


3

In [5]:
tens.dtype

torch.int64

In [6]:
#4d tensor
tens4d=torch.tensor([[[[1.0,2.0],[3.0,4.0]],[[5.0,6.0],[7.0,8.0]]],[[[9.0,10.0],[11.0,12.0]],[[13.0,14.0],[15.0,16.0]]]])
print(tens4d)
tens.ndim

tensor([[[[ 1.,  2.],
          [ 3.,  4.]],

         [[ 5.,  6.],
          [ 7.,  8.]]],


        [[[ 9., 10.],
          [11., 12.]],

         [[13., 14.],
          [15., 16.]]]])


3

### random tensor


In [7]:

rand3dtensor=torch.rand(3,3,2)#create a random 3d tensor
rand3dtensor

tensor([[[0.1574, 0.9544],
         [0.3970, 0.1125],
         [0.2756, 0.2344]],

        [[0.9017, 0.7422],
         [0.0969, 0.0459],
         [0.4107, 0.1161]],

        [[0.2818, 0.4314],
         [0.3311, 0.9573],
         [0.5381, 0.0315]]])

In [8]:
rand3dtensor.shape

torch.Size([3, 3, 2])

In [9]:
#5d random tensor
rand5dtensor=torch.rand(2,3,4,5,6)
rand5dtensor

tensor([[[[[2.4617e-02, 8.6939e-01, 8.7256e-01, 8.2013e-01, 6.9382e-01,
            3.9905e-02],
           [2.0381e-01, 1.2868e-01, 5.6793e-01, 9.9261e-01, 5.3406e-02,
            6.3921e-01],
           [1.2477e-02, 1.1038e-01, 9.6383e-01, 2.9878e-01, 4.7035e-01,
            2.5712e-01],
           [3.4386e-01, 9.8746e-01, 8.2203e-01, 8.1283e-01, 5.7959e-01,
            4.2113e-01],
           [5.3648e-01, 9.9873e-01, 2.0106e-02, 7.6898e-01, 6.4259e-02,
            2.9768e-01]],

          [[7.5617e-01, 4.1196e-01, 7.1015e-01, 7.0698e-01, 3.7130e-01,
            6.1179e-01],
           [4.6016e-01, 1.9229e-01, 2.3473e-01, 4.9677e-01, 5.1179e-01,
            7.7094e-01],
           [2.2715e-01, 7.2326e-01, 7.6062e-01, 2.3951e-02, 4.8855e-01,
            3.4508e-01],
           [1.5345e-01, 9.6069e-01, 9.0106e-01, 9.4545e-01, 4.8890e-01,
            8.9674e-01],
           [4.6829e-01, 6.8184e-01, 1.7359e-01, 5.1243e-03, 2.7508e-01,
            7.3421e-01]],

          [[6.7140e-01, 2.

In [10]:
#zero tensor
zero_tensor=torch.zeros(3,3,3)
zero_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

### data types

In [11]:
zero_tensor.dtype

torch.float32

In [12]:
#float 16 tensor
float16_tensor=torch.zeros(3,3,3,dtype=torch.float16)
float16_tensor.dtype

torch.float16

In [13]:
#float 64 tensor
float64_tensor=torch.zeros(3,3,3,dtype=torch.float64)
float64_tensor.dtype

torch.float64

In [14]:
float16_tensor*float64_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)

In [15]:
# int tensor
int_tensor=torch.tensor([1,2,3,4,5])#default int tensor is int64
int_tensor.dtype

torch.int64

In [16]:
#32 bit int tensor
int32_tensor=torch.tensor([1,2,3,4,5],dtype=torch.int32)#for 16 bit use torch.int16 and for 64 bit use torch.int64


In [17]:
#def function to check dtype device and shape of tensor
def describe_tensor(tensor):
    print(f"Shape of tensor: {tensor.shape}")
    print(f"Datatype of tensor: {tensor.dtype}")
    print(f"Device tensor is stored on: {tensor.device}")


In [18]:
describe_tensor(int32_tensor)

Shape of tensor: torch.Size([5])
Datatype of tensor: torch.int32
Device tensor is stored on: cpu


### tensor manipulating

tensor opretions include:
* airthmatic alzebra
* matrix multipliction



In [19]:
#addition
int_tensor=torch.tensor([1,2,3,4,5])
int_tensor+10

tensor([11, 12, 13, 14, 15])

In [20]:
#multiplication
int_tensor*10

tensor([10, 20, 30, 40, 50])

In [21]:
#by pytorch inbuilt function
torch.add(int_tensor,10)

tensor([11, 12, 13, 14, 15])

In [22]:
torch.mul(int_tensor,10)

tensor([10, 20, 30, 40, 50])

### matrix multiplication
* matrix multiplication 
* elemental multiplication

In [23]:
# element wise multiplication
a=torch.tensor([1,2,3,4,5])
b=torch.tensor([10,20,30,40,50])
a*b

tensor([ 10,  40,  90, 160, 250])

In [24]:
# element wise multiplication in 2d tensor
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.tensor([[10,20,30],[40,50,60]])
print(a,'*',b,)
print(f"equals:{a*b}")

tensor([[1, 2, 3],
        [4, 5, 6]]) * tensor([[10, 20, 30],
        [40, 50, 60]])
equals:tensor([[ 10,  40,  90],
        [160, 250, 360]])


matrix multiplication

In [25]:
#matrix multiplication
a=torch.tensor([[1,2,3],[4,5,6]])#2x3
b=torch.tensor([[10,20],[30,40],[50,60]])#3x2
torch.matmul(a,b)

tensor([[220, 280],
        [490, 640]])

## stat of tensor

In [26]:
# finding mean, max, min, sum, std 2d tensor
def stat_tensor(tensor):
    print(f"Shape of tensor: {tensor.shape}")
    print(f"Datatype of tensor: {tensor.dtype}")
    print(f"Device tensor is stored on: {tensor.device}")
    print(f"Mean: {tensor.mean()}")# means works on float tensor
    print(f"Max: {tensor.max()}")
    print(f"Min: {tensor.min()}")
    print(f"Sum: {tensor.sum()}")
    print(f"Standard Deviation: {tensor.std()}")
a=torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]])
stat_tensor(a)

Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Mean: 3.5
Max: 6.0
Min: 1.0
Sum: 21.0
Standard Deviation: 1.8708287477493286
