To introduce NumPy, we can provide a brief description in the markdown cell. Here's the content for the new cell:

```markdown
NumPy is a powerful Python library for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy is widely used in scientific computing, data analysis, and machine learning tasks.

Key features of NumPy include:
- Efficient array operations: NumPy arrays are faster and more memory-efficient than Python lists, making them ideal for handling large datasets.
- Broadcasting: NumPy allows for element-wise operations between arrays of different shapes, automatically broadcasting the smaller array to match the shape of the larger array.
- Linear algebra operations: NumPy provides a comprehensive set of functions for performing linear algebra operations, such as matrix multiplication, eigenvalue decomposition, and solving linear equations.
- Integration with other libraries: NumPy seamlessly integrates with other scientific computing libraries in Python, such as SciPy, Pandas, and Matplotlib.

To use NumPy in your Python code, you need to import the library using the following statement:
```


In [1]:
import numpy as np
#we have imported numpy as np

In [2]:
np1=np.array([10,20,30,40,50])#all element are of same type
print(np1)

[10 20 30 40 50]


In [3]:
np1.shape#shape of array

(5,)

In [4]:
np2=np.arange(10, 51, 10)  # it will create an array from 10 to 50 with a step of 10
np2

array([10, 20, 30, 40, 50])

In [5]:
np3=np.zeros(5) #it will create an array of 5 elements with all elements as 0
np3

array([0., 0., 0., 0., 0.])

In [6]:
np4=np.ones(5) #it will create an array of 5 elements with all elements as 1
np4

array([1., 1., 1., 1., 1.])

In [7]:
np5=np.linspace(10,50,5) #it will create an array of 5 elements from 10 to 50
np5

array([10., 20., 30., 40., 50.])

In [8]:
#multidimensional
np6=np.zeros((2,3)) #it will create a 2x3 matrix with all elements as 0
np6

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np7=np.full((2,3),5) #it will create a 2x3 matrix with all elements as 5
np7

array([[5, 5, 5],
       [5, 5, 5]])

In [10]:
lst=[[1,2,3],[4,5,6],[7,8,9]]
np8=np.array(lst) #it will create a 2D array from list
np8

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## slicing

In [11]:
np1[0:3] #it will return elements from 0 to 2

array([10, 20, 30])

In [12]:
#steps
np1[0:5:2] #it will return elements from 0 to 4 with step of 2

array([10, 30, 50])

In [13]:
#2d array slicing
np8[0:2,0:2] #first input is for rows and second input is for columns


array([[1, 2],
       [4, 5]])

In [14]:
#pulling out an element from 2d array
print(np8)
np8[1,1] #it will return 5

[[1 2 3]
 [4 5 6]
 [7 8 9]]


5

# universal fuction in numpy

In [15]:
sqrtnp1=np.sqrt(np1) #it will return square root of each element
print("np1 is ",np1)
sqrtnp1

np1 is  [10 20 30 40 50]


array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [16]:
absnp1=np.abs(np1) #it will return absolute value of each element
absnp1

array([10, 20, 30, 40, 50])

In [17]:
#min max
np1.min()

10

In [18]:
np1.max()

50

In [19]:
#positive negative array multidimensional and zero included
np8=np.array([[-1,-2,3],[4,-5,6],[7,0,9]])
print(np.sign(np8))#it will return 1 for positive, -1 for negative and 0 for 0

[[-1 -1  1]
 [ 1 -1  1]
 [ 1  0  1]]


In [20]:
#mathmatical functions
np.sin(np8) #it will return sin of each element

array([[-0.84147098, -0.90929743,  0.14112001],
       [-0.7568025 ,  0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.        ,  0.41211849]])

In [21]:
#log
np.log(np8) #it will return log of each element
#nan means not a number

C:\Users\karan\AppData\Local\Temp\ipykernel_25880\240894305.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(np8) #it will return log of each element
C:\Users\karan\AppData\Local\Temp\ipykernel_25880\240894305.py:2: RuntimeWarning: invalid value encountered in log
  np.log(np8) #it will return log of each element


array([[       nan,        nan, 1.09861229],
       [1.38629436,        nan, 1.79175947],
       [1.94591015,       -inf, 2.19722458]])

# copy vs view

In [22]:
np10=np8.view() #it will create a view of np8
#view is a shallow copy
#change in view will change the original array and vice versa
print(f'orignal np8',np8)
print(f'view of np8',np10)
np10[0,0]=100
print(f'orignal np8',np8)
print(f'view of np8',np10)


orignal np8 [[-1 -2  3]
 [ 4 -5  6]
 [ 7  0  9]]
view of np8 [[-1 -2  3]
 [ 4 -5  6]
 [ 7  0  9]]
orignal np8 [[100  -2   3]
 [  4  -5   6]
 [  7   0   9]]
view of np8 [[100  -2   3]
 [  4  -5   6]
 [  7   0   9]]


In [23]:
#copy
np11=np8.copy() #it will create a deep copy
#change in copy will not change the original array and vice versa
print(f'orignal np8',np8)
print(f'copy of np8',np11)
np11[0,0]=1000#changing copy not changing original
print(f'orignal np8',np8)
print(f'copy of np8',np11)

orignal np8 [[100  -2   3]
 [  4  -5   6]
 [  7   0   9]]
copy of np8 [[100  -2   3]
 [  4  -5   6]
 [  7   0   9]]
orignal np8 [[100  -2   3]
 [  4  -5   6]
 [  7   0   9]]
copy of np8 [[1000   -2    3]
 [   4   -5    6]
 [   7    0    9]]


# shape and reshape

In [24]:
#create 1d numpy array and get shape
np1=np.array([10,20,30,40,50])
print(np1)
print(np1.shape)

[10 20 30 40 50]
(5,)


In [25]:
#2d numpy array
np2=np.array([[10,20,30],[40,50,60]])
print(np2)
print(np2.shape)

[[10 20 30]
 [40 50 60]]
(2, 3)


In [26]:
#3d numpy array
np3=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print(np3)
print(np3.shape)#first is for most outer bracket, second is for middle bracket and third is for inner bracket

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
(2, 2, 3)


In [27]:
#reshape
np1=np.arange(1,11)
print(np1)#it will create an array from 1 to 10
np2=np1.reshape(2,5)#it will reshape the array to 2x5 in manner of row wise
print(np1)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
np1=np.arange(1,13)
print(np1)#it will create an array from 1 to 12
np3=np1.reshape(2,2,3)#it will reshape the array to 2x2x3 in manner of row wise
print(np3)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [29]:
#revert back to 1d array
np4=np3.reshape(-1) #12 can also be used in place of -1 but if we put -2 it will give error
print(np4)
np5=np3.reshape(-2)#no error will be there it will be same as -1
np5

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Iterate

In [30]:
#iterating through numpy array
np1=np.array([10,20,30,40,50])
for i in np1:
    print(i)

10
20
30
40
50


In [31]:
np2=np.array([[10,20,30],[40,50,60]])
for i in np.array(np2):
    print(i)#it will print each row

[10 20 30]
[40 50 60]


In [32]:
for i in np.array(np2):
    for j in i:
        print(j)#it will print each element

10
20
30
40
50
60


# sorting
We use NumPy sorting instead of built-in sorting for several reasons:

1. Performance: NumPy sorting algorithms are highly optimized and can handle large arrays efficiently. They are implemented in C, which makes them faster than the built-in sorting functions in Python.

2. Multidimensional sorting: NumPy provides functions to sort arrays along specific axes or dimensions. This is particularly useful when working with multidimensional arrays, as it allows us to sort the data based on specific criteria for each dimension.

3. In-place sorting: NumPy sorting functions can sort the array in-place, meaning that the original array is modified directly without creating a new sorted array. This can be more memory-efficient and faster for large arrays.

4. Custom sorting criteria: NumPy sorting functions allow us to specify custom sorting criteria using the `key` parameter. This allows us to sort the array based on specific elements or attributes of the array elements.

Overall, NumPy sorting provides more flexibility, performance, and functionality compared to the built-in sorting functions in Python.


In [33]:
#sorting
np1=np.array([50,30,40,10,20])
np.sort(np1)#it will sort the array


array([10, 20, 30, 40, 50])

In [34]:
#alphabetical sorting
np1=np.array(['banana','apple','cherry'])#it will sort the array in manner of alphabetical order like apple, banana, cherry in dictionary
np1=np.sort(np1)
print(np1)

['apple' 'banana' 'cherry']


In [35]:
#boolean sorting
np1=np.array([True,False,True])
np1=np.sort(np1)    #it will sort the array in manner of false, true
print(np1)

[False  True  True]


In [36]:
#sorting is copy not view
np1=np.array([50,30,40,10,20])
np2=np.sort(np1)
print(np1)
print(np2)

[50 30 40 10 20]
[10 20 30 40 50]


In [37]:
#multi dimensional sorting
np1=np.array([[50,30,40],[10,20,60]])
np2=np.sort(np1)
print(np1)
print(np2)


[[50 30 40]
 [10 20 60]]
[[30 40 50]
 [10 20 60]]


# searching

In [38]:
#searching in numpy array
np1=np.array([10,20,30,40,50,30])
x=np.where(np1==30)#it will return the index of 30
print(x)#x is tuple
print(x[0])#it will return the index of 30
print(np1[x[0]])#it will return the value at index of 30


(array([2, 5], dtype=int64),)
[2 5]
[30 30]


In [39]:
 # even odd
np1=np.array([10,25,30,40,50,30])
x=np.where(np1%2==0)#it will return the index of even numbers
print(x)#x is tuple
print(x[0])#it will return the index of even numbers    
print(np1[x[0]])#it will return the value at index of even numbers

(array([0, 2, 3, 4, 5], dtype=int64),)
[0 2 3 4 5]
[10 30 40 50 30]


# filtring nupy array

In [40]:
# filter numpy array with boolean index list
np1=np.array([10,25,30,40,50,30])
filter=np.array([True,False,True,True,False,True])# true if for which we want to keep the element
#why we use true fasle array because we can use it for any condition
print(filter)
newarr=np1[filter]#it will return the elements for which filter is true
print(newarr)

[ True False  True  True False  True]
[10 30 40 30]


In [41]:
np1=np.array([10,25,30,40,50,30])
filter=[]
for i in np1:#it will return true if element is even
    if i%2==0:
        filter.append(True)
    else:
        filter.append(False)    
#filter=[True if i%2==0 else False for i in np1]
print(np1[filter])


[10 30 40 50 30]
