In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F


import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import numpy as np
import pandas as pd

In [4]:
l=np.random.randn(1,10)

In [5]:
l

array([[-0.19869242, -0.9983455 ,  0.30293458, -0.90647874,  0.49086198,
        -1.40278986,  0.94714725,  1.05483638, -0.10140176, -0.60201231]])

In [21]:
k=l.reshape((1,5,2)).ravel()


In [19]:
k=np.array(k)

In [17]:
k=[1,2,3,4,5,6,7,8,9,10]

In [22]:
if isinstance(k, np.ndarray):
    print("arr is a numpy array")
else:
    print("arr is not a numpy array")

arr is a numpy array


In [36]:
arr_2d = np.array(np.array([[[ 1,2, 3], [4, 5, 6], [7, 8, 9]]]))

In [37]:
arr_2d_1 =  np.array(np.array([[[ 1,2, 3], [4, 5, 6], [7, 8, 9]]]))

In [38]:
arr_2d+arr_2d_1

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])

In [40]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr_1d_2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a=np.array([arr_1d,arr_1d_2])
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])